package com.oracle.carshop.model.bean;
import java.io.Serializable;

/**
 * 车辆图片 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CarImage implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 图片编号. */
	private Integer imageid;

	/** 汽车编号. */
	private Integer carid;

	/** 图片路径. */
	private String imagepath;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public CarImage() {
	}

	/**
	 * 图片编号 傪愝掕偟傑偡.
	 * 
	 * @param imageid
	 *            图片编号
	 */
	public void setImageid(Integer imageid) {
		this.imageid = imageid;
	}

	/**
	 * 图片编号 傪庢摼偟傑偡.
	 * 
	 * @return 图片编号
	 */
	public Integer getImageid() {
		return this.imageid;
	}

	/**
	 * 汽车编号 傪愝掕偟傑偡.
	 * 
	 * @param carid
	 *            汽车编号
	 */
	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	/**
	 * 汽车编号 傪庢摼偟傑偡.
	 * 
	 * @return 汽车编号
	 */
	public Integer getCarid() {
		return this.carid;
	}

	/**
	 * 图片路径 傪愝掕偟傑偡.
	 * 
	 * @param imagepath
	 *            图片路径
	 */
	public void setImagepath(String imagepath) {
		this.imagepath = imagepath;
	}

	/**
	 * 图片路径 傪庢摼偟傑偡.
	 * 
	 * @return 图片路径
	 */
	public String getImagepath() {
		return this.imagepath;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((imageid == null) ? 0 : imageid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CarImage other = (CarImage) obj;
		if (imageid == null) {
			if (other.imageid != null) {
				return false;
			}
		} else if (!imageid.equals(other.imageid)) {
			return false;
		}

		return true;
	}

}
