--<ScriptOptions statementTerminator=";"/>

CREATE TABLE chaye (
	CHAYEID INT NOT NULL,
	MINGZI VARCHAR(50),
	YUANJIA INT,
	XIANJIA INT,
	SHOUTU VARCHAR(200),
	PINGLUNSHU INT,
	PRIMARY KEY (CHAYEID)
) ENGINE=MyISAM;

