
/* Drop Tables */

DROP TABLE RELATION;
DROP TABLE PRODUCT;
DROP TABLE TAOBAO_USER;
DROP TABLE PRODUCT_BILL;




/* Create Tables */

CREATE TABLE PRODUCT
(
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	PRODUCT_NAME NVARCHAR2(10),
	PRODUCT_NUM NUMBER(10,0),
	PRODUCT_IMG VARCHAR2(100),
	PRODUCT_PRICE NUMBER,
	PRIMARY KEY (PRODUCT_ID)
);


CREATE TABLE PRODUCT_BILL
(
	BILL_ID NUMBER(10,0) NOT NULL,
	USER_NAME NVARCHAR2(10),
	PRIMARY KEY (BILL_ID)
);


CREATE TABLE RELATION
(
	PRODUCT_ID NUMBER(10,0) NOT NULL UNIQUE,
	BILL_ID NUMBER(10,0) NOT NULL UNIQUE
);


CREATE TABLE TAOBAO_USER
(
	-- 用户id
	USER_ID NUMBER(6,0) NOT NULL,
	USER_NAME NVARCHAR2(10),
	PASSWORD NCHAR(18),
	BILL_ID NUMBER(10,0) NOT NULL UNIQUE,
	PRIMARY KEY (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE RELATION
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES PRODUCT (PRODUCT_ID)
;


ALTER TABLE RELATION
	ADD FOREIGN KEY (BILL_ID)
	REFERENCES PRODUCT_BILL (BILL_ID)
;


ALTER TABLE TAOBAO_USER
	ADD FOREIGN KEY (BILL_ID)
	REFERENCES PRODUCT_BILL (BILL_ID)
;



/* Comments */

COMMENT ON COLUMN TAOBAO_USER.USER_ID IS '用户id';


alter table chaye 
add column tuiguang int(1) default 0;

rollback;
select * from chaye;